<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="model">

	<xacro:property name = "base_mass" value = "1.0"/>
	<xacro:property name = "base_height" value = "0.05"/>
	<xacro:property name = "base_radius" value = "0.1"/>

	<xacro:property name = "mount_height" value = "0.2"/>
	<xacro:property name = "mount_length" value = "0.05"/>
	<xacro:property name = "mount_width" value = "0.02"/>
	<xacro:property name = "mount_mass" value = "0.5"/>

	<xacro:property name = "elbow_mass" value = "0.5"/>
	<xacro:property name = "elbow_width" value = "0.02"/>
	<xacro:property name = "elbow_height" value = "0.05"/>
	<xacro:property name = "elbow_length" value = "0.10"/>



	<link name = "world"/>
	<link name = "base_link">
		<inertial> 
			<mass value = "${base_mass}"/>
			<origin xyz = "0 0 0" rpy = "0 0 0"/> 
			<inertia ixx = "0.0" 
				 	 ixy = "0.0" 
				 	 ixz = "0.0"
				  	 iyy = "0.0" 
				 	 iyz = "0.0" 
				  	 izz="0.0"/>
		</inertial>

		<visual name = "base_link_visual">
			<origin xyz = "0 0 0" rpy = "0 0 0" />
			<geometry>
				<cylinder length = "${base_height}" radius = "${base_radius}"/>
			</geometry>
		</visual>

		<collision name = "base_link_collision">
			<origin xyz = "0 0 0" rpy = "0 0 0"/>
			<geometry>
				<cylinder length = "${base_height}" radius = "${base_radius}"/>
			</geometry>
		</collision>
	</link>


	<link name = "mount_link">
		<inertial>
			<mass value="${mount_mass}"/>
				<origin xyz = "${base_radius + mount_width/2} 0 ${-mount_height/2+base_height/2}" />
			<inertia ixx = "0.0"
					 ixy = "0.0"
					 ixz = "0.0"
				     iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0"/>
		</inertial>

		<visual name = "mount_link_visual">
			<origin xyz = "${base_radius + mount_width/2} 0 ${-mount_height/2+base_height/2} "/>
			<geometry>
				<box size = "${mount_width} ${mount_length} ${mount_height}"/>
			</geometry>
		</visual>

		<collision name = "mount_link_collision">
			<origin xyz = "${base_radius + mount_width/2} 0 ${-mount_height/2+base_height/2}"/>
			<geometry>
				<box size = "${mount_width} ${mount_length} ${mount_height}"/>
			</geometry>
		</collision>
	</link>


	<link name = "elbow_link">
		<inertial>
			<mass value = "${elbow_mass}"/>
				<origin xyz = "${mount_length} 0 0 "/>
			<inertia ixx = "0.0"
					 ixy = "0.0"
					 ixz = "0.0"
					 iyy = "0.0"
					 iyz = "0.0"
					 izz = "0.0"/>
			</inertial>

		<visual name = "elbow_link_visual">
			<origin xyz = "${base_radius} 0 ${-mount_length}" />
			<geometry> 
				<box size = "${elbow_width} ${elbow_length} ${elbow_height}"/>
			</geometry>
		</visual>

		<visual name = "second_elbow_link">
			<origin xyz = "${base_radius} ${base_radius} ${-mount_height}"/>
			<geometry>
				<box size = "${elbow_width} ${elbow_length} ${elbow_height}"/>
			</geometry>
		</visual>
		
		<collision name = "elbow_link_collision">
			<origin xyz = "${base_radius} ${base_radius} ${-mount_height}"/>
			<geometry>
				<box size = "${elbow_width} ${elbow_length} ${elbow_height}"/>
			</geometry>
		</collision>
	</link>

	<joint name = "pitch_joint" type = "revolute">
		<parent link = "mount_link" />
		<child link = "elbow_link" />
		<origin xyz = "${base_radius} ${base_radius} ${-mount_length}"/>
		<axis xyz = "1 0 0" />
		<limit lower="${-pi/4}" upper="${pi/4}" effort="1000.0" velocity="10.0"/>
	</joint>

	<joint name = "yaw_joint" type = "continuous">
		<parent link = "base_link" />
		<child link = "mount_link" />
		<axis xyz = "0 0 1" />
	</joint>

	<joint name="world_joint" type="fixed">
		<parent link="world"/>
		<child link="base_link"/>
		<origin xyz = "0 0 1" rpy = "0 0 0"/>
	</joint>
</robot>