model:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 40

  pitch_controller:
    type: position_controllers/JointPositionController
    joint: pitch_joint
    pid: {p: 10.0, i: 1.0, d: 0.5}

  yaw_controller:
    type: position_controllers/JointPositionController
    joint: yaw_joint
    pid: {p: 10.0, i: 1.0, d: 0.5}

  roll_controller:
    type: position_controllers/JointPositionController
    joint: roll_joint
    pid: {p: 10.0, i: 1.0, d: 0.5}